[project]
name = "khive"
version = "0.4.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "fastmcp>=2.11.3",
    "lionagi[graph,postgres,rich,schema, sqlite]>=0.15.5",
    "nest-asyncio>=1.6.0",
    "openai>=1.99.9",
    "plotly>=6.3.0",
    "pydantic-settings>=2.10.1",
    "pyyaml>=6.0.2",
    "streamlit>=1.48.1",
    "tenacity>=9.1.2",
    "websockets>=15.0.1",
]

[tool.pytest.ini_options]
addopts = "-ra --cov=khive --cov-report=term-missing"
testpaths = ["tests"]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "pre-commit>=4.3.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.9",
]

[tool.hatch.build.targets.wheel]
packages = ["src/khive"]

[project.scripts]                # PEP 621 console-scripts table
khive         = "khive.cli.khive_cli:main"
