name: KhiveServices
description: A service for multiple groups.

groups:
  info_service:
    name: "khive-info"
    class_path: "src.khive.services.info.info_service:InfoServiceGroup"
    description: "A group for searching information online and consult with experts."

  reader_service:
    name: "khive-reader"
    class_path: "src.khive.services.reader.reader_service:ReaderServiceGroup"
    description: "A group for reading, parsing urls structured and unstructured files"
