# Project-specific configuration
enable = ["python", "docs"]

[stacks.python]
cmd = "ruff format {files}"
check_cmd = "uv run ruff format --check {files}"
include = ["*.py"]
exclude = [
    "*_generated.py",
    ".venv/**",
    "venv/**",
    "env/**",
    ".env/**",
    "**/.venv/**",
    "**/venv/**",
    "**/env/**",
    "**/.env/**",
    "node_modules/**",
    "**/node_modules/**",
    "target/**",
    "**/target/**",
    "__pycache__/**",
    "**/__pycache__/**",
    "*.pyc",
    ".git/**",
    ".pytest_cache/**",
    ".mypy_cache/**",
    ".ruff_cache/**",
    "build/**",
    "dist/**",
    "*.egg-info/**",
    ".tox/**",
    ".coverage",
    "htmlcov/**",
    "site-packages/**",
    "**/site-packages/**",
]

[tool."khive fmt".stacks.docs]
cmd = "deno fmt {files}"
check_cmd = "deno fmt --check {files}"
include = ["*.md", "*.markdown"]
exclude = []
